"""init

Revision ID: 21d3a524a0c8
Revises: 
Create Date: 2025-04-14 09:44:54.262613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d3a524a0c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arduinos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arduino_id', sa.Integer(), nullable=False),
    sa.Column('index_capteur', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('adresse_mac', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['arduino_id'], ['arduinos.id'], name='fk_sensor_arduino_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('localites', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nom',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('code_postal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_nom_code_postal', ['nom', 'code_postal'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('arduino_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('Value0',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value1',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value2',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value3',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value4',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value5',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value6',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value7',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value8',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('Value9',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_log_arduino_id', 'arduinos', ['arduino_id'], ['id'])

    with op.batch_alter_table('meteo_previsions', schema=None) as batch_op:
        batch_op.alter_column('localite_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('date_heure_utc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('wind_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('wind_dir',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('wind_gusts_1h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('wind_gusts_24h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('temp',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('temp_max',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('temp_min',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pression',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pluie_1h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pluie_24h',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('uv',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('lever_soleil',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('coucher_soleil',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_meteo_previsions_localite_id', 'localites', ['localite_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('birthdate',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('birthdate',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('meteo_previsions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meteo_previsions_localite_id', type_='foreignkey')
        batch_op.alter_column('coucher_soleil',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lever_soleil',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('uv',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('pluie_24h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('pluie_1h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('pression',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('temp_min',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('temp_max',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('temp',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('wind_gusts_24h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('wind_gusts_1h',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('wind_dir',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('wind_speed',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('date_heure_utc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('localite_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_log_arduino_id', type_='foreignkey')
        batch_op.alter_column('Value9',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value8',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value7',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value6',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value5',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value4',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value3',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value2',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value1',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Value0',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('arduino_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('localites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_nom_code_postal', type_='unique')
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('code_postal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nom',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('sensors')
    op.drop_table('arduinos')
    # ### end Alembic commands ###
