"""create bank operations and categories

Revision ID: 4311e14096bc
Revises: 21d3a524a0c8
Create Date: 2025-04-17 16:28:55.418647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4311e14096bc'
down_revision = '21d3a524a0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('sous_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categorie_id', 'nom', name='uq_categorie_souscat')
    )
    op.create_table('bank_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('sous_categorie_id', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('person', sa.String(length=50), nullable=True),
    sa.Column('source_file', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sous_categorie_id'], ['sous_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_operations')
    op.drop_table('sous_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
