"""create bank tables with prefixed categories

Revision ID: 8de45160f5d0
Revises: 4311e14096bc
Create Date: 2025-04-17 16:35:36.850054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de45160f5d0'
down_revision = '4311e14096bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('bank_sous_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['bank_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categorie_id', 'nom', name='uq_bank_categorie_souscat')
    )
    op.drop_table('sous_categories')
    op.drop_table('categories')
    with op.batch_alter_table('bank_operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bank_categories', ['categorie_id'], ['id'])
        batch_op.create_foreign_key(None, 'bank_sous_categories', ['sous_categorie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sous_categories', ['sous_categorie_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['categorie_id'], ['id'])

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('sous_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('categorie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categorie_id', 'nom', name='uq_categorie_souscat')
    )
    op.drop_table('bank_sous_categories')
    op.drop_table('bank_categories')
    # ### end Alembic commands ###
